app.name=Libreria Eviden
spring.application.name=Libreria-Grupo-3-Back
server.port=8089

# Keycloak Configuration

jwt.auth.converter.resource-id= backend
jwt.auth.converter.principal-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri= http://localhost:9099/realms/library
spring.security.oauth2.resourceserver.jwt.jwk-set-uri= http://localhost:9099/realms/library/protocol/openid-connect/certs

#logging

logging.level.org.keycloak=DEBUG
logging.level.com.backend.library.backend = DEBUG
logging.file.name=library.log

# Spring Data JPA Configuration

spring.datasource.url= jdbc:postgresql://localhost:5432/libreria
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username= postgres
spring.datasource.password= 123456

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= create-drop

# Swagger Spring Docs Configuration

springdoc.api-docs.enabled= true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

#Pay Pal
#use #sandbox for testing and #live for production
paypal.baseUrl=https://api-m.sandbox.paypal.com
paypal.mode=sandbox
paypal.client.id=AU9d5Oz60cf-hup6rsKAJzBPTeTucwI3b_6mDUyVswQUxvb7-hCWB_X0gL5OPovn2p8drV2lVWob3PRT
paypal.client.secret=EHrDiG3RsUF6rFbiT3M_SwpAdJPPbaVMwUWBaqeahrg6gp_aoh-T5poHdF6jaaqn0Qvhf_u6ok8jHsgd
paypal.success.url=http:localhost:8089/api/v1/payment/success
paypal.cancel.url=http:localhost:8089/api/v1/payment/cancel


#email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khalifa.boulbayem.eviden@gmail.com
spring.mail.password=Eviden2024?
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


